"""add stock quantity to product

Revision ID: d201dd224c4c
Revises: b66903e8fda4
Create Date: 2026-09-01 01:18:10.421298

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'd201dd224c4c'
down_revision: Union[str, Sequence[str], None] = 'b66903e8fda4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('stock_quantity', sa.Integer(), nullable=True))
    op.drop_constraint(op.f('product_ibfk_1'), 'product', type_='foreignkey')
    op.create_foreign_key(None, 'product', 'manufacturer', ['manufacturer_id'], ['id'])
    op.create_foreign_key(None, 'product_category', 'category', ['category_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'product_category', type_='foreignkey')
    op.drop_constraint(None, 'product', type_='foreignkey')
    op.create_foreign_key(op.f('product_ibfk_1'), 'product', 'manufacturer', ['Manufacturer_id'], ['id'])
    op.drop_column('product', 'stock_quantity')
    # ### end Alembic commands ###
