"""initial table

Revision ID: b66903e8fda4
Revises: 
Create Date: 2026-09-01 00:26:33.196977

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'b66903e8fda4'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('manufacturer_id', sa.Integer(), nullable=True))
    op.drop_constraint(op.f('product_ibfk_1'), 'product', type_='foreignkey')
    op.create_foreign_key(None, 'product', 'manufacturer', ['manufacturer_id'], ['id'])
    op.drop_column('product', 'Manufacturer_id')
    op.create_foreign_key(None, 'product_category', 'category', ['category_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'product_category', type_='foreignkey')
    op.add_column('product', sa.Column('Manufacturer_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'product', type_='foreignkey')
    op.create_foreign_key(op.f('product_ibfk_1'), 'product', 'manufacturer', ['Manufacturer_id'], ['id'])
    op.drop_column('product', 'manufacturer_id')
    # ### end Alembic commands ###
